name: ActionsCI

env:
  Configuration: Release

on:
  push:
    branches: [master, develop]

jobs:
  build-windows-qt68:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '[17,18)'  # 17.xx
        msbuild-architecture: x64
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version:      6.8.2
        host:         windows
        target:       desktop
        modules:      qtmultimedia
        setup-python: false
        
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        
    - name: Download Botan
      run: |
        curl -L -o botan.zip https://github.com/randombit/botan/archive/refs/tags/3.7.1.zip
        tar -xvf botan.zip
        cd botan-3.7.1
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        set CL=/MP
        python configure.py --cc=msvc --os=windows --build-tool=ninja --disable-modules=sqlite3
        ninja
        ninja check
        ninja install

    - name: build
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        set CL=/MP
        cmake -S . -B build -G "Ninja Multi-Config"
        cmake --build build --config Release
        
    - name: deploy
      run:  |
        windeployqt.exe --no-compiler-runtime --release build/src/Release/shredder.exe
        
    - name: cleaning
      shell: cmd
      run:  |
        xcopy ${{ github.workspace }}\README.md build\src\Release
        rmdir /s /q build\src\Release\generic
        rmdir /s /q build\src\Release\networkinformation
        rmdir /s /q build\src\Release\translations
        rmdir /s /q build\src\Release\tls
        del /F build\src\Release\Qt6Network.dll
        del /F build\src\Release\D3Dcompiler_47.dll
        del /F build\src\Release\opengl32sw.dll

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: shredder.zip
        path: build/src/Release
